cask "rapidkey@0.2.0" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.2.0'
  sha256 "c6fc952f1b34ce55b585d0e4e0b1be39780478f4e10c6229e7e59836c274e287"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
