cask "rapidkey@0.1.1" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.1.1'
  sha256 "40c9453603487513f6c96a7307c71c9ffaacbd262060be7d115426d6bcf468cb"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
