cask "rapidkey@0.1.2" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.1.2'
  sha256 "ab5d13a2390f92b00b5d7d37f860fda7c915cc08a892432c4be54ed228f27994"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
