cask "rapidkey@0.2.1" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.2.1'
  sha256 "2aaddaba03965bd93f5770246b840c3964b876b103b3fb03641b559b3a4b4750"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  # During upgrade: remember if RapidKey was running, quit before replacing the app bundle,
  # then relaunch the new version in postflight.
  uninstall preflight do
    if system("pgrep -xq RapidKey")
      File.write("/tmp/rapidkey-was-running", "1")
    end
  end

  uninstall quit: "RapidKey"

  postflight do
    app_path = "#{appdir}/RapidKey.app"
    system "xattr -d com.apple.quarantine #{app_path} 2>/dev/null || true"

    flag = "/tmp/rapidkey-was-running"
    if File.exist?(flag)
      File.delete(flag)
      system "open", app_path
    end
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
