cask "rapidkey@0.3.2" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.3.2'
  sha256 "9e072f08e7feb9f6a1c9c3aae4d068c545319e6dd492b91a5eef458e64ac883d"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  # Quit before upgrade/replace; Homebrew reopens the app after upgrade if quit succeeded.
  uninstall quit: "org.soniejka.RapidKey"

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app 2>/dev/null || true"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
