cask "rapidkey@0.1.4" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.1.4'
  sha256 "7dafca73cb4da8fa14fc0af73a7491ab5e18879710b80e3f46747de1e0af9fd8"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
