cask "rapidkey@0.2.2" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.2.2'
  sha256 "069b77a3d6a3928c77d17e33951d90c481ca63f0ce1ab1891626df7cb3372cf2"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  # Quit before upgrade/replace; Homebrew reopens the app after upgrade if quit succeeded.
  uninstall quit: "org.soniejka.RapidKey"

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app 2>/dev/null || true"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
