cask "rapidkey@0.1.0" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.1.0'
  sha256 "5003c1ec84f80d0e218c4041ce9174dcfc0240f74c107c4f8280fe1211fe823b"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
