cask "rapidkey@0.3.0" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.3.0'
  sha256 "ba3aed02f77196038f4386c0b324c0030f537cac7be90c0aec8a409b87f90584"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  # Quit before upgrade/replace; Homebrew reopens the app after upgrade if quit succeeded.
  uninstall quit: "org.soniejka.RapidKey"

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app 2>/dev/null || true"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
