cask "rapidkey@0.1.3" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.1.3'
  sha256 "d2a08cd6fc5919d06df7f7dd6e21ba84e7a7dedae8ca9d8ae5b9628b2c064dd6"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
