cask "rapidkey@0.1.5" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.1.5'
  sha256 "35c8839249df0b87bd36bd612152d31d655e56a8e858f8c6728fa80207be66ae"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
