cask "rapidkey@0.2.4" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.2.4'
  sha256 "8aa3012c3e4c42f432ce5f473247f7a1dd0993f9503829852a2906d5c999c6ca"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  # Quit before upgrade/replace; Homebrew reopens the app after upgrade if quit succeeded.
  uninstall quit: "org.soniejka.RapidKey"

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app 2>/dev/null || true"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
