cask "rapidkey@0.2.3" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.2.3'
  sha256 "d978d63f21ebdbcced92b74bf1a370b57702ef9d18fe228df890a68a01649518"

  url "https://github.com/ivalkou/rapidkey/releases/download/v#{version}/RapidKey-v#{version}.zip"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/ivalkou/rapidkey"

  depends_on macos: ">= :sequoia" # macOS 15

  # Quit before upgrade/replace; Homebrew reopens the app after upgrade if quit succeeded.
  uninstall quit: "org.soniejka.RapidKey"

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app 2>/dev/null || true"
  end

  app "RapidKey-v#{version}/RapidKey.app"
end
